package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.41

import (
	"adtec/backend/src/graphql/generated"
	"adtec/backend/src/graphql/model"
	"adtec/backend/src/router/profileRouter"
	"context"
	"fmt"
)

// CreateProfile is the resolver for the createProfile field.
func (r *mutationResolver) CreateProfile(ctx context.Context, input model.CreateProfileInput) (*model.Profile, error) {

	// TODO:the userId should be fetched from the current user token
	// ctx = context.WithValue(ctx, srcModel.ConfigKey("currentUser"), currentUser)

	return profileRouter.Create(ctx, input)
}

// Profile is the resolver for the profile field.
func (r *queryResolver) Profile(ctx context.Context) (*model.Profile, error) {
	panic(fmt.Errorf("not implemented: Profile - profile"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
